services:
  learning-vim:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: learning-vim
    tty: true
    stdin_open: true
    working_dir: /home/appuser/workspace
    user: "appuser"
    volumes:
      - .devcontainer/vimrc:/home/appuser/.config/vim/vimrc:rw
      - .:/home/appuser/workspace:cached
#   ports:
#     - "8888:8888"  # optional: run `jupyter lab` inside container on 8888
#     - "5678:5678"  # Optional: to allow Debugger to access the code running in DevContainer via debugpy
#     - "22:7676"    # To enable SSH tunneling through the host into Raspberry Pi
    command: /bin/zsh
    environment:
      TZ: "Europe/Zurich"
      LANG: "${LANG:-en_US.UTF-8}"
      LANGUAGE: "${LANGUAGE:-en_US.UTF-8}"
      LC_ALL: "${LC_ALL:-en_US.UTF-8}"
