services:
  learning-vim:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: learning-vim
    tty: true
    stdin_open: true
    working_dir: /home/appuser/workspace
    user: "appuser"
    volumes:
      - ../.devcontainer/vimrc:/home/appuser/.config/vim/vimrc:rw
      - ..:/home/appuser/workspace:cached
    command: /bin/zsh
    environment:
      TZ: "Europe/Zurich"
      LANG: "${LANG:-en_US.UTF-8}"
      LANGUAGE: "${LANGUAGE:-en_US.UTF-8}"
      LC_ALL: "${LC_ALL:-en_US.UTF-8}"
